### PR TITLE
Add some more startup vars

### PR DESCRIPTION
**Pull request by brantje**
- Add env var for world size
- Add env var for maximum players	
- Add env var for save interval

### CODE REVIEW

**Comment by brantje** [comment]
Fixes #4

**Comment by Dids** [comment]
@brantje Could you set default world size to 3500 and default max players to 500? Just so that they're identical to the defaults that Rust uses out of the box.

I'll merge the changes after that. Also thanks. :)

**Comment by brantje** [comment]
No problem, needed the world size for my server.
So while i was busy i didn't mind to add the other ones.

**Comment by Dids** [comment]
The build is now available. You can pull it with `docker pull didstopia/rust-server`.

**Pull request merged**
