### PR TITLE
start_rust.sh

### PR DESCRIPTION
**Pull request by mdarkness1988**
Added the ability to change SteamID for login. 
Use Variable STEAMID

### CODE REVIEW

**Comment by Dids** [comment]
Hmm, did you test if this still works for anonymous logins? Might also want to add `STEAMID` to the Dockerfile, just for readability, but potentially also to set defaults (eg. `STEAMID` could default to `anonoymous`, right?).

**Comment by mdarkness1988** [comment]
Yh.  After this update I changed the dockerfile and I had made the option to use anonymous instead. 
Would you like the files?

**Comment by Dids** [comment]
If you push the changes to the `patch-3` branch on your fork, they'll automatically be added here, which is the preferred way of doing pull requests.

**Comment by mdarkness1988** [comment]
Update: after working on this,  I got it to work and if blank value it defaulted to anonymous but found out afterwards rust won't let u use ur steam account as always get error saying "No Subscription". 
So all that work got wasted. 

Sorry to waits your time :)

**Pull request closed without merging**
